### ISSUE TITLE
Comment System in PHP or JQuery and Other Pages

### ISSUE THREAD

**Issue by Taki21** [StarCoders/starcoders.github.io#1]
@AmiroEmad 
@StarCoders/devs 

I need help to finish all this! xD

And with other pages

**Comment by MiroTheSuperDev** [comment]
I will make a better website for here but when I have free time please make this github org a Dev team not a server

**Comment by Taki21** [comment]
o_0 really

**Comment by Taki21** [comment]
I can just add a page for downlaods...

**Comment by Taki21** [comment]
@AmiroEmad ur too generous xD
however i wanna keep the current one
(btw im slow in web codin (html css etc...))
I can add a devs page too

**Comment by remotevase** [comment]
I'll add a simple login portal. Not the nicest looking button, but it'll do... Which page should I add it to, and @Taki21 tell me the password in our conversation on ImagicalMine forums. (Don't worry, its all html. Just need to type password, and it redirects to a dev page)

**Comment by Taki21** [comment]
umm? whaah

**Comment by Taki21** [comment]
I mean like people login with their email u know those buttons like
Sign in with Email
xD
@remotevase Thx for suggestion though lol
Actually i am a long way from that step lets finish the rest than do it :P

**Comment by Taki21** [comment]
LOL ADDED SLIDESHOW XD

**Comment by Taki21** [comment]
@remotevase Im afraid the login system u made is not workin! 
Do u mind if i try a different method and see if it works???
Im gonna start so ill revert if it doesnt work :/
xD

**Comment by remotevase** [comment]
of course! BTW my login system is a problem with the css files...

**Comment by Taki21** [comment]
xD

**Comment by MiroTheSuperDev** [comment]
to do login and register system you need a database that is set remotly to github and have a good amount of quota and this thing is hard to find for free 

so i advice you go to byet.host

register an account you will get all features you need plus unlimited database

**Comment by remotevase** [comment]
Amiro wasnt talking about php and database. I just wanted users to enter a password (same for everyone) in order to access the staff website

**Comment by MiroTheSuperDev** [comment]
maybe github would support that but i am not sure if that would work

**Comment by remotevase** [comment]
Goodness, @AmiroEmad read the whole conversation! I have login systems, but they're messed up by the css files !

**Comment by MiroTheSuperDev** [comment]
i read it all before i comment

**Comment by MiroTheSuperDev** [comment]
do you have a problem if i made the website have a minecraft theme

**Comment by remotevase** [comment]
That would be nice
