### ISSUE TITLE
Someone Help ME!

### ISSUE THREAD

**Issue by Taki21** [StarCoders/StarCoders.github.io#1]
@StarCoders/devs 
ANyone now how to setup github pages!?
havin problems....xD

**Comment by TheKnightGamer** [comment]
What do you mean?

**Comment by remotevase** [comment]
https://github.com/StarCoders/starnetwork.github.io/generated_pages/new

**Comment by TheDragonRing** [comment]
If you still we'd help @Taki21 then just send me the text you want and I'll set it up for you : ) although it is pretty easy xD

**Comment by Taki21** [comment]
@TheDragonRing Commited to DIsableCmds

**Comment by Taki21** [comment]
@remotevase 
I mean like how everyone codes it not make it xD

**Comment by remotevase** [comment]
Oh XD

**Comment by TheDragonRing** [comment]
@Taki21 just do a html file with a couple of css files and if needed for an image an image file

**Comment by remotevase** [comment]
Use github page generator, then get rid of all the coding in index.HTML! Once that's all gone, we are starting from scratch

**Comment by TheDragonRing** [comment]
OHHHHHHHHHH JUST REALISED YOUR BIG FAT MISTAKE XD. You named the repo starnetwork.github.io it should be starcoders.github.io it has to be same name as the organisation/team or it has to be in a gh-pages branch and the URL would be starcoders.github.io/repo-name

**Comment by TheDragonRing** [comment]
I just renamed

**Comment by TheDragonRing** [comment]
And capitals matter when putting in the URL and naming the repo to name.github.io

**Comment by TheDragonRing** [comment]
Ok why is it still not working......

**Comment by TheDragonRing** [comment]
I'll just use the auto page generator and then replace the Index.html with the current one and see if that works...

**Comment by TheDragonRing** [comment]
It works! It works! Now edit the index.html to your hearts content xD

**Comment by Taki21** [comment]
omg thx

**Comment by ImagicalGamer** [comment]
:+1: Awesome!

**Comment by Taki21** [comment]
@remotevase 
@TheDragonRing 
Thx so muxh! For help

**Comment by TheDragonRing** [comment]
No problem : )

**Comment by TheDragonRing** [comment]
Era, not sure if anyone's noticed but all the websites for StarNetwork are off-centre, half of the site is outside the screen, not sure if anyone has had this problem tho

**Comment by remotevase** [comment]
Yup, @Taki21 should be fixing that soon... Should also be more mobile friendly...

**Comment by Taki21** [comment]
U mean the blank white thingy?
