### ISSUE TITLE
slideshow

### ISSUE THREAD

**Issue by MiroTheSuperDev** [StarCoders/starcoders.github.io#3]
slide show ishiding nav bar

**Comment by Taki21** [comment]
??? which page?

**Comment by Taki21** [comment]
Send a Image Please! Gotta see it!

**Comment by AmiroEmad** [comment]
![Uploading Untitled.png…]()

**Comment by MiroTheSuperDev** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15315415/14092727/4c795aaa-f549-11e5-9bea-94006323aea8.png)

**Comment by Taki21** [comment]
holy cow!

**Comment by Taki21** [comment]
Wait a sec...Are  u in normal zoom? Or is it when u just go to the website it appears like dat?

**Comment by Taki21** [comment]
I see it like this
![ice_screenshot_20160329-072700](https://cloud.githubusercontent.com/assets/14851895/14106547/d75e12ec-f57f-11e5-9a38-d486c2434da6.png)

**Comment by Taki21** [comment]
Hmm...I see our resulotions are different
so im gonna have to fix for resolution for phones and other Screen Ratios As Well

**Comment by Taki21** [comment]
@AmiroEmad Can u provide the screen width in pixels of your monitor? Thats the only way to fix it

**Comment by Taki21** [comment]
Fixed
