### ISSUE TITLE
Page is toto all

### ISSUE THREAD

**Issue by dragonwocky** [StarCoders/starcoders.github.io#4]

**Comment by Taki21** [comment]
Ok xD I said  I would do earlier but I changed the files so i started over xD 
gonna search up how to fix...xD

**Comment by dragonwocky** [comment]
You could use and then edit templates from TEMPLATED.co, I did it with BoxOfBits and it looks much better than it used to

**Comment by Taki21** [comment]
Ok Im gonna fix soon! Figured out a solution!
