### ISSUE TITLE
need help with date

### ISSUE THREAD

**Issue by ghost** [StarCoders/starcoders.github.io#6]
function date(){
			var time = new Date()
			var month = time.getMonth();			
			var date = time.getDate();
			var fullyear = time.getFullYear();
		}
this is what i got but i dont know how to exactly use it.....
(i found this online)

**Comment by Taki21** [comment]
to use it
use 
document.getElementById({element_name}').innerHTML = date();

**Comment by ghost** [comment]
function startTime() {
			var time = new Date();
			var hour = time.getHours();			
			var minute = time.getMinutes();
			var second = time.getSeconds();
			hour = hour % 12;
			if (hour < 1){
				hour = 12;
			}
			minute = checkTime(minute);
			second = checkTime(second);
			document.getElementById('time').innerHTML = hour + ":" + minute + ":" + second;		

			var t = setTimeout(startTime, 50);
		}
		
		function checkTime(i) {
			if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
			return i;
		}


<div id="time" style="color:DarkBlue;font-size:36px;"></div>

**Comment by ghost** [comment]
<div id="time" style="color:DarkBlue;font-size:36px;"></div>
this is da html

**Comment by ghost** [comment]
THE HTML ISNT GOING ON

**Comment by Taki21** [comment]
oh u using military time nvm lol

**Comment by Taki21** [comment]
wth i know how to java script xd

**Comment by AvgZing** [comment]
shhp tomorrow we'll code

**Comment by ghost** [comment]
Srry even for my webpage I made time but date just didn't work outside I
gave up 😭😭😭😭😭😭

**Comment by ghost** [comment]
*out

**Comment by Taki21** [comment]
lol

**Comment by Taki21** [comment]
@Asif6474 @Asif4287 
can u welp us with the website too?

**Comment by AvgZing** [comment]
@Taki21 We got it Just us dudez

**Comment by AvgZing** [comment]
Like old times :)

**Comment by AvgZing** [comment]
Like 2 years ago, just the two of us colab ing on a project

**Comment by Taki21** [comment]
lol ik but asif is cousin xd
